#!/bin/bash

set -e

RUNALL=false


while [ $# -gt 0 ] ; do
  case $1 in
    --runAll) RUNALL=true ;;
    --runSimple) RUNALL=false;;
    \-? ) echo "Usage: runTest"
          echo "  --runAll: Run all test cases and view result at report/testReport.html"
          echo "  --runSimple: Run only catch2 test cases"
  esac
  shift
done


currDir=$(pwd)


function checkParaView {
if ! command -v pvpython &> /dev/null; then
    echo "  ** pvpython seems to be not installed **"
    echo "  Not generating figures from advection test case"
else
    pvpython createFigures.py
fi
}

function runAll {
    # ---------------------------------------------------------------------------
    #                      Run Test Cases - Single Processor
    # ---------------------------------------------------------------------------

    cd ${currDir}/Cases/2DMesh
    blockMesh > /dev/null
    ../../src/WENO_TEST [baseTest]
    
    [[ -d "constant/WENOBase3" ]] && rm -r constant/WENOBase3
    ../../src/WENO_TEST [IOTest]

    # Clean up 
    [[ -e "PLOT/results.dat" ]] && rm PLOT/results.dat
    [[ -d "constant/WENOBase3" ]] && rm -r constant/WENOBase3

    # run with WENO 3 0
    sed -i "s/WENOUpwindFit.*/WENOUpwindFit 3 0;/" system/fvSchemes
    sed -i "s/bestConditioned.*/bestConditioned false;/" system/WENODict
    sed -i "s/writeData.*/writeData     true;/" system/WENODict
    sed -i "s/^nCells.*/nCells 100;/" system/blockMeshDict && blockMesh > /dev/null && ../../src/WENO_TEST [upwindFitTest]

    # run with WENO 3 0 read in data
    sed -i "s/WENOUpwindFit.*/WENOUpwindFit 3 0;/" system/fvSchemes
    sed -i "s/bestConditioned.*/bestConditioned false;/" system/WENODict
    sed -i "s/writeData.*/writeData     false;/" system/WENODict
    sed -i "s/^nCells.*/nCells 100;/" system/blockMeshDict && blockMesh > /dev/null && ../../src/WENO_TEST [upwindFitTest]
    [[ -d "constant/WENOBase3" ]] && rm -r constant/WENOBase3

    # run with WENO 4 0
    sed -i "s/WENOUpwindFit.*/WENOUpwindFit 4 0;/" system/fvSchemes
    sed -i "s/bestConditioned.*/bestConditioned false;/" system/WENODict
    sed -i "s/^nCells.*/nCells 100;/" system/blockMeshDict && blockMesh > /dev/null && ../../src/WENO_TEST [upwindFitTest]

    # run with WENO 3 0 bestConditioned
    sed -i "s/WENOUpwindFit.*/WENOUpwindFit 3 0;/" system/fvSchemes
    sed -i "s/bestConditioned.*/bestConditioned true;/" system/WENODict
    sed -i "s/^nCells.*/nCells 100;/" system/blockMeshDict && blockMesh > /dev/null && ../../src/WENO_TEST [upwindFitTest]

    # run with WENO 4 0 bestConditioned
    sed -i "s/WENOUpwindFit.*/WENOUpwindFit 4 0;/" system/fvSchemes
    sed -i "s/bestConditioned.*/bestConditioned true;/" system/WENODict
    sed -i "s/^nCells.*/nCells 100;/" system/blockMeshDict && blockMesh > /dev/null && ../../src/WENO_TEST [upwindFitTest]

    cd PLOT/ && gnuplot plotReport.gplt
    
    cd ${currDir}/Cases/2DMesh-cyclic
    sed -i "s/^nCells.*/nCells 100;/" system/blockMeshDict && blockMesh > /dev/null && ../../src/WENO_TEST [upwindFitTest]

    cd ${currDir}/Cases/2DMesh-cyclicAMI
    sed -i "s/^nCells.*/nCells 100;/" system/blockMeshDict && blockMesh > /dev/null && ../../src/WENO_TEST [upwindFitTest]


    cd ${currDir}/Cases/advectionCase
    blockMesh > /dev/null 
    ../../src/WENO_TEST [Advection]
    mkdir -p Figures
    checkParaView

    # ---------------------------------------------------------------------------
    #                      Run Test Cases - MPI Processor
    # ---------------------------------------------------------------------------
    cd ${currDir}/Cases/globalFvMeshTestCase/case-3D
    blockMesh > /dev/null && decomposePar -force > /dev/null 
    mpirun -np 8 ../src/globalFvMeshTest.exe -parallel 
}



function runSimple {
    # ---------------------------------------------------------------------------
    #                      Run Test Cases - Single Processor
    # ---------------------------------------------------------------------------

    cd ${currDir}/Cases/2DMesh-cyclic
    blockMesh > /dev/null
    ../../src/WENO_TEST [baseTest]
    
    [[ -d "constant/WENOBase3" ]] && rm -r constant/WENOBase3
    ../../src/WENO_TEST [IOTest]

    # Clean up 
    [[ -e "PLOT/results.dat" ]] && rm PLOT/results.dat
    [[ -d "constant/WENOBase3" ]] && rm -r constant/WENOBase3

    # run with WENO 3 0
    sed -i "s/WENOUpwindFit.*/WENOUpwindFit 3 0;/" system/fvSchemes
    sed -i "s/bestConditioned.*/bestConditioned false;/" system/WENODict
    sed -i "s/writeData.*/writeData     true;/" system/WENODict
    sed -i "s/^nCells.*/nCells 100;/" system/blockMeshDict && blockMesh > /dev/null && ../../src/WENO_TEST [upwindFitTest]
    


    # ---------------------------------------------------------------------------
    #                      Run Test Cases - MPI Processor
    # ---------------------------------------------------------------------------
    cd ${currDir}/Cases/globalFvMeshTestCase/case-3D
    blockMesh > /dev/null && decomposePar -force > /dev/null 
    mpirun -np 8 ../src/globalFvMeshTest.exe -parallel 
}
# ---------------------------------------------------------------------------
#                           Compile Libray
# ---------------------------------------------------------------------------


if [[ $RUNALL == true ]]; then
    runAll
else
    runSimple
fi



