FROM jgaertner2/openfoam:v2006

CMD [ "/bin/sh" ]

# Add the library src to our build env
# FROM env AS devel
# Create lib directory
RUN mkdir -p /home/gitlab/build/
WORKDIR /home/gitlab/build


# Bundle lib source
COPY --chown=gitlab:gitlab . .

# Update git submodules
RUN git submodule init && git submodule update

# First compile the code
RUN . $foamDotFile && ./Allwclean && ./Allwmake -f -j

# Run all unit tests
RUN . $foamDotFile && cd tests && ./runTest
