name: C/C++ CI

on:
  push:
    branches: [ master, dev-v3.x, dev-CI]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: OpenFOAM8
      run: make runTestsOF8
