name: C/C++ CI

on:
  push:
    branches: [ master, dev-CI]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: OpenFOAMv1912
      run: make runTestsOFv1912
